In [4]:
print ("hello Jupiter")

hello Jupiter


In [18]:
2+2

4

In [19]:
"Hello"

'Hello'

In [20]:
# NumPy

In [30]:
import numpy as np

In [22]:
# Установка NumPy
!pip install numpy

In [23]:
# создание списка
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [24]:
np.array(my_list)

array([1, 2, 3, 4])

In [28]:
my_array = np.array(my_list)

In [29]:
my_array

array([1, 2, 3, 4])

In [30]:
# создание списка из нулей
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
z.dtype

dtype('float64')

In [33]:
np.zeros(10, dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [34]:
np.zeros(10, dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [35]:
np.zeros(10, dtype="int64").dtype

dtype('int64')

In [36]:
# 2-мерный массив с формой 2 на 3 (2 строки и 3 столбца)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Вектор как линейная последовательность
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
np.arange(0,20,2).reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [41]:
# Вектор как массив из равномерно распределенных значений
# например, от 0 до 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
# массив размером 3 * 5
# Случайные значения из равномерно распределенного диапозона от 0 до 1
np.random.random(5)

array([0.57157004, 0.48899102, 0.70885652, 0.38390086, 0.15948406])

In [44]:
np.random.random((3,5)).astype("float16")

array([[0.5947 , 0.05844, 0.1543 , 0.988  , 0.5103 ],
       [0.2573 , 0.9507 , 0.01515, 0.313  , 0.1486 ],
       [0.1819 , 0.805  , 0.2491 , 0.03702, 0.1573 ]], dtype=float16)

In [46]:
# массив  с целочисленными случайными значениями
np.random.randint(10)

2

In [47]:
np.random.randint(10,20)

16

In [48]:
np.random.randint(10, size = 5)

array([2, 8, 3, 2, 3])

In [54]:
np.random.randint(10, 20, size = (3,5))

array([[19, 18, 12, 11, 11],
       [18, 19, 13, 14, 13],
       [14, 13, 10, 11, 12]])

•Аттрибуты

In [55]:
a1 = np.random.randint(10, 20, size = (3,5))
a1

array([[16, 17, 10, 19, 12],
       [15, 18, 14, 16, 16],
       [15, 17, 12, 16, 17]])

In [56]:
# размерность массива (кол-во измерений/осей)
a1.ndim

2

In [57]:
# форма массива
a1.shape

(3, 5)

In [58]:
# размерность массива (кол-во элементов массива)
a1.size

15

In [59]:
# тип значений массивы
a1.dtype

dtype('int32')

•Индексация

In [64]:
a2 = np.random.randint(10,size=10)
a2

array([1, 8, 9, 2, 7, 0, 9, 1, 3, 3])

In [65]:
a2[0]

1

In [66]:
a2[-1]

3

In [69]:
a3 = np.random.randint(10,size=(2,3))
a3

array([[1, 8, 4],
       [1, 6, 7]])

In [70]:
a3[0, 1]

8

- Срезы

In [67]:
a2[:5]

array([1, 8, 9, 2, 7])

In [71]:
a2[1:]

array([8, 9, 2, 7, 0, 9, 1, 3, 3])

In [72]:
a2[1:6:2]

array([8, 2, 0])

In [73]:
a3[0,1:]

array([8, 4])

In [74]:
a3[:,1:]

array([[8, 4],
       [6, 7]])

In [3]:
# Срез списка
my_list =[1,2,3,4,5]
sub_list = my_list[2:]

In [6]:
# Срез массива
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [45]:
sub_arr = my_array[2:]
sub_arr

array([  3, 500, 500])

In [46]:
sub_arr is my_array

False

In [47]:
# массив созданый срезом из другого массива, является представлениям
sub_arr[-1] = 500
sub_arr

array([  3, 500, 500])

In [48]:
my_array

array([  1,   2,   3, 500, 500])

In [50]:
# копия массива
sub_arr_2[-1] = my_array[2:].copy()
sub_arr_2

NameError: name 'sub_arr_2' is not defined

In [35]:
sub_arr_2[-1] = 100
sub_arr_2

NameError: name 'sub_arr_2' is not defined

In [39]:
my_array

array([  1,   2,   3, 500, 500])

- Изменение формы

In [40]:
# 1-мерный массив(вектор-строка)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr.shape

(9,)

In [42]:
# создание вектор-столбца
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [43]:
# 2-мерный массива(матрица)
my_shape = (3,3) #кортеж со значениями будущего массива (кол-во строк, кол-во столбцов)
# arr.reshape(my_shape)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Операции
(универсальные функции)


In [53]:
a = np.arange(5)
b = np.arange(1,6)
print(a)
print(b)

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

In [52]:
# Поэлементное деление
a / b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [55]:
# Адаптер (алиас) оператора "+"
# np.add(a, b)
# a + b

array([1, 3, 5, 7, 9])

- Агрегирование

In [58]:
# Агрегирование - вычисление неких свободных показателей
arr_2 = np.random.random((10))
arr_2

array([0.0938342 , 0.9977948 , 0.89285046, 0.34392656, 0.10932146,
       0.67394914, 0.63801262, 0.68213674, 0.03884585, 0.86042874])

In [60]:
# сумма
# np.sum(arr_2) 1D array
np.sum(arr.reshape(3,3)) #2D array

45

In [61]:
# минимум
np.min(arr_2)

0.03884585291227116

In [62]:
# среднее арифметическое
np.mean(arr_2)

0.5331100569719786

- Сравнения

In [73]:
np.array([1,2,3]) != 2

array([ True, False,  True])

In [88]:
# Имеются ли в массиве какие-либо значения, превышающие 5
x = np.arange(1,10).reshape((3,3))
np.any(x > 5, axis=1)

array([ True,  True, False])

In [89]:
# Все ли значения равны 6
np.all(x < 6, axis=1)

array([ True, False, False])

- Маскирование

In [82]:
# x = np.array([1,2,3,4,5])
x = np.random.randint(10, size=(5,))
x < 3

array([ True, False, False, False,  True])

In [85]:
y = np.array([10,20,30,40,50])
y[x < 3] #массив буллевых значений - маска

array([10, 50])

In [84]:
x[x>3]

array([7, 4])

- Прихотливая индексация

In [92]:
x = np.random.randint(100, size=10)
x

array([81, 34, 58, 31, 63, 44, 68, 32, 17, 85])

In [93]:
# передаем список или массив индексов необходимых значений
x[[3,0,5]]

array([31, 81, 44])

In [94]:
# Если хотил массив по форме индексов
ind = np.array([
    [3,0],
    [1,2]
])
x[ind]

array([[31, 81],
       [34, 58]])